Cloud testapp
Otus-DevOps-2018-02/Edmakas_infra pull request #4
Opened 2018-03-26 13:00 UTC by Edmakas

# Выполнено ДЗ № 5

 - [x ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:

  -  Установлен Google Cloud SDK
  - Развернут инстанс из консоли
  -  Создано правило брандмауэра из консоли
  -  Развернуто приложение на созданном инстансе с помощью startup-script

## Как запустить проект:
 - Вести команды из README.md ДЗ № 5 

## Как проверить работоспособность:
 - Например, перейти по ссылке http://ipaddress:9292

## PR checklisk
 - [x] Выставил label с номером домашнего задания
 - [x ] Выставил label с темой домашнего задания

2018-03-30 05:21 UTC, sedovandrew reviewed
Привет!

Хотелось бы узнать, зачем ты вынес startup script из под системы контроля версий?

2018-03-30 05:29 UTC, sedovandrew requested changes
Внеси startup script в проект, чтобы он изменялся совместно с проектом, как его часть.

В остальном задание выполнено. Увидел дополнительное задание с командой для создания правила брандмауэра.

2018-03-30 11:53 UTC, Edmakas commented
Привет, 
startup_script.sh находится в проекте. Может надо пириминовать  на startup.sh ?

2018-03-30 16:17 UTC, sedovandrew commented
В проекте есть файл `startup_script.sh`, в котором находится команда на скачивание и исполнение скрипта. Сам же скрипт находится не в системе котроля версий. Он может меняться независимо от проекта. Какая причина данный скрипт выносить из проекта, если он имеет к нему непосредственное отношение и может меняться с развитием этого проекта в дальнейшем?

2018-03-31 05:11 UTC, Edmakas commented
Спасибо за замечание -поправил. Теперь всё локально в startup_script.sh

2018-03-31 08:56 UTC, sedovandrew approved these changes

2018-03-31 08:57 UTC, sedovandrew commented
Все условия выполнения ДЗ соблюдены. Дополнительные задания выполнены. Можешь мержить в мастер!

2018-03-31 13:08 UTC, merged