Packer base
Otus-DevOps-2018-02/Edmakas_infra pull request #5
Opened 2018-03-30 15:31 UTC by Edmakas

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
  -  созданные в hw6 скрипты перенесены в каталог config-scripts
  -  создан каталог packer для шаблона ubuntu16.json и подкаталог scripts для скриптов установки сервисов и приложений
  - в соотвествии с заданием параметризованы переменные создания шаблона ВМ

## Как запустить проект:
```
cd packer
packer validate ubuntu16.json 
packer build ubuntu16.json
```

## Как проверить работоспособность:
- выполнить команды на хосте 
```
git clone -b monolith https://github.com/express42/reddit.git
cd reddit && bundle install
puma -d
```
 - перейти по ссылке http://IP:9292

## PR checklisk
 - [x] Выставил label с номером домашнего задания
 - [x]  Выставил label с темой домашнего задания

2018-04-05 03:36 UTC, sedovandrew requested changes
Привет! ДЗ 6 выполнено в полном объёме. Задания со звёздочкой увидел. Есть некоторые мелкие замечания. Подправь, пожалуйста.

2018-04-05 03:36 UTC, sedovandrew commented on packer/immutable.json
> +    "tags": ["puma-server","edamakas-tag"]
Правило брандмауэра `gcloud compute firewall-rules create puma --allow:9292 --target-tags=puma-server` открывает порт 9292. Указанный здесь тег `puma-server` добавляет это правило для инстанса во время запекания. При запуске ВМ указанный тег необходимо будет указывать снова для корректной работы,а здесь даный тег задавать нет необходимости, так как не планируется доступ к ВМ по этому порту во время запекания приложения.

Про тег `edamakas-tag` никаких упоминаний не нашёл. Зачем он здесь?

2018-04-05 03:36 UTC, sedovandrew commented on packer/ubuntu16.json
> +    "tags": "puma-server"
Здесь тоже задавать данный тег нет необходимости.

2018-04-05 03:36 UTC, sedovandrew commented on packer/immutable.json
> +      "script": "files/install_test_app.sh",
А зачем ты положил скрипт `install_test_app.sh` отдельно от остальных скриптов?

2018-04-05 05:00 UTC, Edmakas commented
Спасибо за замечание. Всё поправил

2018-04-06 04:04 UTC, sedovandrew approved these changes

2018-04-06 11:18 UTC, merged

2018-04-06 11:18 UTC, Nklya commented
Смержено для проверки дальше